language: scala

scala:
   - 2.10.6
   - 2.11.8
   - 2.12.1

branches:
  only:
    - master

notifications:
  email:
    - vitaliy.kuznetsov@yahoo.co.uk

jdk:
  - oraclejdk8

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION coverage "$PROJECT/test" coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
