language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

branches:
  only:
  - master

notifications:
  email:
  - vitaliy.kuznetsov@yahoo.co.uk

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out pubring.gpg -d

script:
  - sbt clean coverage test coverageReport publishSigned sonatypeRelease

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
  - secure: NpKxKGwISsmf6hfHdzSqkpaqWb1NDtNJBs+zBq+b7Wdg4Sm7068PGiueMtGSBzakiryd5grntvqqBcjTrbNdLdRn6gDj0TgGfokZij85et/io/hu5X8CGZiTyeqHbqBcNucl/1hyg7Xih2vbHPfYHSuQ56JwDpaDKw0GphankYGXsdkHwib0MKIIvz9Dm1QW1QYRTvvryNjmRUe4Mm2vhtEJ+0C6JHLxGdUhn96Zsn15SPkaWZeDLKt1fZAUsTN1eNkxxcFfB0Oz4AORGuyVyeI39PV3TJ7mG23O5rMuwvsiqNVikKtfYrE54mRUirLYTY6Mt1pEEedVs7IGH9S/sX4vxuqtvoLT8mZcICDPI/QOGIrt1mQQqv9lg3UkSKJb0SSYALGzjyMWYiTz2ivtbmX2/25SGWHA13ClxNHBpySkXZTsR4FHhlbp8qpAv+MGb0rfJd68aAly56l4g+suv2PBeurMOWDKD6bcBpZkNvNT+EDq7DRDJJ5VGOqODJgVrFUoyybWSjTOWis71oBelimrm5K7XYp61Fo3OZQVnq4/MCuLf6+D8veJ1Bk81WkBjXfeFYrcO/H00Ypoj47PZELVjEQuQKKw74G3bICP1vI+pGW78l0WqaYTxibnxTuyr9ERtd5d4pwHtD5SiPgNLi9SYBZf8RIf/6zaApYjbAM=
  - secure: PBLqu/o5v3SXGKnk1uj1Jt6h8BwFXwuaHWMp8XvRAvedXkx4vTVt5b1Kn9rkl3jT8h4tTEkCrtHOLR6Mizn8AeI3vVn+NVMVX/lv4+9xaGNkcactYp1siLt6oBZgRfNnfXh+JLAIMTRPUkLPtOr74wJU+ru8doQ0n3l9dhG6RWZeqjAcDmXoZcEHj7d9xZTLXkyLmtn9Bq/BB1M50olcW8hpJnnqfcQOJwSTvwprGQw6kY75qlTi4jvinHbEjGSpX4mFHcdqBbZBcNad7AAaymrJ48FJDCKH3wm9cYbJYYO3eidFy4cZXnU7seMWaBX/3TiypgEpmuWrlkXYAJ5t7iDsxnyVqybYBo5wgQAOSkB/syE2oTcrvqN9BK+zdvkA0Jtnna2Ay9Bhb4dqHRN2Clfe3e7e5EIjeQocI/fbb6lcqE6C4aqhQmojMSDcEoeo214tt92qRpczEXiIRqHypL34YIwuQIZFy5+MtAUQCSk9xd4mpql2SSJhSAdysOTQGKCW+MURDDiC7b3QE3MmNEuYzYdpJi6BGhP+UwtxxYqTRxfzz62RqcFBOHb/tzls8o2GBmYeIur+RQAPUCymyAqNO+yfVwxWGBTITR8Uq4oqqTsluwigkttxa1ug6BDMZ+SuzSfA+z0K3EJY70HhPjvRtbGmu4hGCXkYq2FfwM8=
  - secure: K2n/++//YDD/Oj7P+ze9IrYv5tbZVfdYQDst/paDEH7g1RjU7AYt6364oLlnaOmH9hhC/0dfjeguOXK6UbTNTRCHbbIKAPgZrHGRGfRpb10xoiWisZjsptiK0mN5W+pVLkTgTS/dzi3DKLSZfDaFQbLh+dp3296mIc/OzrNoqggLQKjEGAUKI0zY96Z1eQANfbgo1kbfB8/d3iLPSO2LCUdTEGEc351WiuCpcEfke0J7eqmwlA/z7YW9iDn9NP2dR2P/4f+0VYUya7hGln0UjkqnzKzZ2EfGwp3C07S9BE6y5MGzC5c8yPnQdRF1+yXsDPhNPrNvfyaD2atUyGwobOU6VGiszOdqKQ5jwOXb+AgZuqHWIyAM480Ip6KMo8IKollLK8bBOvhDOoHX7GI0NqVaWZzhrqocm4y7fv8jJmRxbvBGKkOhxBaEB7HZBzyE/nSNpbqdh5phL7/r3HFH3Fof8kZOmhFBqO82RLP6QKL0Tr50K5S6AcL77cvbActUcGaNRvGLXSxPxv+AtWOXgj1ZjZvTf/WWk0f40GWYe/FGh7p9atMzD0xh24XjgtaRTZxlg0B0vfGdUQN2NdA+RytOm1u2am4DMKoka70OJpCqzmU5Z+0MRId9Jo/tAYaVTuo7t0PaJPACtS0AvaQy3MZG3fWWcwQ8hOiMp7RwdVo=
